var GM_ok_mp3=new Audio("/genius/aud/yes.mp3"),GM_nok_mp3=new Audio("/genius/aud/no.mp3"),GM_enter_chime=new Audio("/genius/aud/enter-chime.mp3"),G_boom_ba_mp3=new Audio("/genius/aud/g-boom-ba.mp3");function gm_play_sound(a){a=a.play();void 0!==a&&a.then(function(b){})["catch"](function(b){})}function gm_get_bootcamp_spelling(){var a="Boomcapt Pootcamb Poatcomb Coatpomb Tacobomp Pambcoot Pombcoat Coatbomp".split(" ");return.5>Math.random()?"Bootcamp":a[Math.floor(a.length*Math.random())]}
function gm_start_countdown(){var a=setInterval(function(){var b=new Date("Aug 1, 2023")-new Date;if(0>b)clearInterval(a),$("#gm-countdown").text="This Bootcamp has started";else{var c=Math.floor(b/864E5),d=Math.floor(b%864E5/36E5),e=Math.floor(b%36E5/6E4);b=Math.floor(b%6E4/1E3);$("#gm-countdown").text(c+" days, "+d+" hours, "+e+" min, "+b+"s left")}},1E3)}var GM_prev_contents=null,GM_yn_button_is_armed=!1;
function gm_arm_yn_button(){gm_play_sound(GM_ok_mp3);$("#gm-yn-div").addClass("gm-yn-ok");$("#gm-yn-input").addClass("gm-yn-ok");GM_yn_button_is_armed=!0}function gm_disarm_yn_button(){gm_play_sound(GM_nok_mp3);$("#gm-yn-div").removeClass("gm-yn-ok");$("#gm-yn-input").removeClass("gm-yn-ok");GM_yn_button_is_armed=!1}function gm_yn_font_resize(){var a=$("#gm-yn-input").val();a=20>=a.length?33:33-.5*(a.length-20);12>a&&(a=12);$("#gm-yn-input").css("font-size",a+"px")}
function gm_onkeyup_yn(a){if(null!=a){var b=$("#gm-yn-input").val().trim().toLowerCase();if(27==a.which&&""!=$("#gm-yn-input").val())$("#gm-yn-input").val(""),b="",gm_disarm_yn_button();else if(13==a.which||10==a.which){if(!GM_yn_button_is_armed)return;$("#gm-bootcamp").text(gm_get_bootcamp_spelling());"yes"==b?$("#gm-yn-feedback").html("YES was the correct answer.<br>Have fun questing with other Geniuses!<br><br>"):$("#gm-yn-feedback").html("NO was the WRONG answer.<br>Find out why by joining other Geniuses having fun.<br><br>");
gm_play_sound(GM_enter_chime);gm_show_name_email_div()}else"yes"!=b&&"no"!=b||"yes"==GM_prev_contents||"no"==GM_prev_contents?"yes"==b||"no"==b||"yes"!=GM_prev_contents&&"no"!=GM_prev_contents||gm_disarm_yn_button():gm_arm_yn_button();gm_yn_font_resize();GM_prev_contents=b}}var GM_name_email_button_armed=!1;function gm_email_is_valid(){var a=$("#gm-email").val();return a?/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(a):!1}function gm_name_is_valid(){return""!=$("#gm-name").val().trim()}
function gm_arm_button(){gm_play_sound(GM_ok_mp3);$("#gm-name-email-entry-div").addClass("gm-entry-ok");$("#gm-name").addClass("gm-valid-name");$("#gm-email").addClass("gm-valid-email");GM_name_email_button_armed=!0}function gm_disarm_button(){gm_play_sound(GM_nok_mp3);$("#gm-name-email-entry-div").removeClass("gm-entry-ok");$("#gm-name").removeClass("gm-valid-name");$("#gm-email").removeClass("gm-valid-email");GM_name_email_button_armed=!1}
function gm_button_check(){gm_email_is_valid()&&gm_name_is_valid()?GM_name_email_button_armed||(gm_arm_button(),GM_name_email_button_armed=!0):GM_name_email_button_armed&&(gm_disarm_button(),GM_name_email_button_armed=!1)}function gm_name_email_font_resize(){var a=$("#gm-name").val().length;a=18>=a?24:432/a;$("#gm-name").css("font-size",a+"px");a=$("#gm-email").val().length;a=18>=a?24:432/a;$("#gm-email").css("font-size",a+"px")}
function gm_onkeyup_email(a){null!=a&&(27==a.which&&""!=$("#gm-email").val()?($("#gm-email").val(""),gm_disarm_button()):(13==a.which||10==a.which?GM_name_email_button_armed&&gm_process_rego():gm_button_check(),gm_name_email_font_resize()))}function gm_onkeyup_name(a){null!=a&&(27==a.which&&""!=$("#gm-name").val()?($("#gm-name").val(""),gm_disarm_button()):(13==a.which||10==a.which?GM_name_email_button_armed&&gm_process_rego():gm_button_check(),gm_name_email_font_resize()))}
function gm_process_rego(){gm_play_sound(G_boom_ba_mp3);var a=$("#gm-name").val().trim(),b=$("#gm-email").val().trim().toLowerCase();url="/genius/php/gm-process-applicant.php";param={n:a,e:b};$.post(url,param,function(c){c=JSON.parse(c);gm_show_rego_status(null==c||0>=c.n?1729:c.n)})}
$(document).ready(function(){$("body").fadeIn();$("#gm-yn-input").focus();$("#gm-yn-input").keyup(gm_onkeyup_yn);$("#gm-name").keyup(gm_onkeyup_name);$("#gm-email").keyup(gm_onkeyup_email);$("#gm-genii").click(function(){gm_show_genii()});$("#gm-name-email-overlay-x").click(function(){gm_dismiss_name_email_div()});$("#gm-rego-status-overlay-x").click(function(){gm_dismiss_rego_status()});$("#gm-genii-overlay-x").click(function(){gm_dismiss_genii()});gm_start_countdown()});
function gm_show_name_email_div(){$("#gm-yn-input").prop("disabled",!0);$("#gm-name-email-overlay").fadeIn(1500);$("#gm-name").focus()}function gm_dismiss_name_email_div(){$("#gm-yn-input").prop("disabled",!1);$("#gm-name-email-overlay").fadeOut()}
function gm_show_rego_status(a){0>a?alert("Oops! Something went wrong. Please contact the administrators. Thanks"):($("#gm-waitlist-number").text("#"+a),$("#gm-name").prop("disabled",!0),$("#gm-email").prop("disabled",!0),$("#gm-rego-status-overlay").fadeIn())}function gm_dismiss_rego_status(){$("#gm-rego-status-overlay").fadeOut();$("#gm-name").prop("disabled",!1);$("#gm-email").prop("disabled",!1)}function gm_show_genii(){$("#gm-genii-overlay").fadeIn()}
function gm_dismiss_genii(){$("#gm-genii-overlay").fadeOut()};

