var _ra=null,_rm={},_rb="",_rc=0,_rd=[],_re=[],_rf=!0,_rg=!0,_rh=LORE_EDITABLE,_ri=null,_rj=null,TR_backup_lines=null,_rk="https://d3vn5blk9ekwpv.cloudfront.net",_rl=new Audio("/res/mp3/misc/elevator-music-03-60s.mp3");$(document).ready(function(){$(window).resize(function(){_rg=!0});$("#tr-curtain").height($(window).height());$("#tr-curtain").width($(window).width());_tf1()});
function _tf1(){$("#tr-home-button").click(function(){_tf8();window.setTimeout(function(a){window.location="/"},250)});$("#tr-play-button").click(_tf4);$("#tr-pause-button").click(_tf8);url_params=new URLSearchParams(window.location.search);url_params.has("id")?(console.log("Here is the lore you asked me for"),id=url_params.get("id")):(console.log("Here is the lore for whenever you're bored"),id="dd4a8ee14cea7458390e9f3b87d28a52");_rh&&_tf18();if(id.match(/^[0-9a-f]{32}$/)){var a=_rk+"/cache/"+id;
console.log("Cache hit: "+a);$.get(a,_tf2)}else console.log("Hitting server for: "+id),$.post("https://quests.nonlinearmedia.org/php/tr_get_lore.php",{id:id},_tf2);window.setInterval(_tf3,50);$("#tr-curtain").fadeOut(3E3)}
function _tf2(a){"string"==typeof a&&(a=JSON.parse(a));if("error"in a){if(0!=a.error){console.log(a);return}a=a.data}a&&a["in"]||(a["in"]={title:"Untitled",subtitle:"Unsubtitled",lines:["UNWRITTEN: Say less and thus say more"],speaker_map:{}});$("#tr-title").html(a["in"].title);$("#tr-subtitle").html(a["in"].subtitle);_tf20(a["in"].lines);_rm=null==a["in"].speaker_map?{}:a["in"].speaker_map;_rh?_tf17():a.out.cache_id&&_tf14(a.out.cache_id);null!=a.out.audio_objects&&0<a.out.audio_objects.length&&
(_ra=a.out.audio_objects);$("#tr-lore-container").scroll(function(){_rf=!0});$("#tr-lore-trail-selector").scroll(function(){_rf=!0});_rf=!0;_tf12()}function _tf3(){_tf16();_tf32();_tf33()}
function _tf4(){var a=_tf21();_tf25(_ri,a)||(_ra=null,_ri=a);if(null!=_ra)_tf5(),_tf4_from_current_position();else{var c=_tf27(),b;for(b in c)_rm&&b in _rm||(console.log("Assigning voice actor Joanna for speaker: "+b),_rm[b]="Joanna");a={command:"do_synthesis","in":{title:$("#tr-title").html(),subtitle:$("#tr-subtitle").html(),lines:a,speaker_map:_rm}};_tf9();$.post("https://4cdi46fse8.execute-api.us-west-1.amazonaws.com/Prod/tr",JSON.stringify(a),function(a){_tf10();if(a&&a.data&&a.data.out){var b=
a.data.out;b.audio_objects&&0!=b.audio_objects.length&&b.cache_id?(_ra=b.audio_objects,_rb=b.cache_id,_tf13(_rb),_rh||_tf14(_rb),_rc=0,_tf4_from_current_position()):(console.log("do_synth returned an unusable result"),console.log(a))}else console.log("do_synth returned an unusable result"),console.log(a)})}}function _tf5(){_rc=void 0;for(var a=$("#tr-lore-container").height(),c=$(".tr-message"),b=0;b<c.length;b++)if($(c[b]).offset().top>a/2){_rc=b;break}void 0==_rc&&(_rc=0)}
function _tf6(){var a=$("#tr-lore-container").height();a=$(".tr-message")[_rc].offsetTop-a/2;$("#tr-lore-container").animate({scrollTop:a},"ease")}
function _tf4_from_current_position(){if(null==_ra||"undefined"==typeof _ra)console.log("Play invoked when script is null");else if(_rc>=_ra.length)_tf8();else{_tf6();_tf11();var a=_rk+"/audio/",c=_ra[_rc],b=c[0].match(/^http.*[.]mp3$/)?c[0]:a+c[0]+".mp3";audio=new Audio(b);"undefined"==typeof audio?console.log("Could not load "+b):(_re.push(audio),0==c[1]?audio.onended=_tf4_from_current_position:(a=window.setTimeout(_tf4_from_current_position,100),_rd.push(a)),_rc++,a=audio.play(),void 0!==a&&a.then(function(a){})["catch"](function(a){console.log("play("+
b+") failed")}))}}function _tf8(){for(;0<_re.length;){var a=_re.pop();a.onended=null;$(a).animate({volume:0},1E3)}for(;0<_rd.length;)a=_rd.pop(),clearTimeout(a);_tf12()}function _tf9(){_rl=new Audio("/res/mp3/misc/elevator-music-03-60s.mp3");_rl.loop=!0;$("#tr-curtain").fadeIn();var a=_rl.play();void 0!==a&&a.then(function(a){})["catch"](function(a){console.log("play(elev_01) failed")});$("#tr-curtain-nebula").css({animation:"tr-img-spin infinite","animation-duration":"120s"})}
function _tf10(){$("#tr-curtain").fadeOut(3E3,function(){$("#tr-curtain-nebula").stop(!0,!0)});$(_rl).animate({volume:0},1E3)}function _tf11(){$("#tr-pause-button").show();$("#tr-play-button").hide();$("#tr-lore-container").css({overflow:"hidden"})}function _tf12(){$("#tr-pause-button").hide();$("#tr-play-button").show();$("#tr-lore-container").css({overflow:"auto"})}function _tf13(a){a="https://lores.nonlinearmedia.org/?id="+a;$("#tr-permalink").html(a).attr("href",a)}
function _tf14(a){$("#tr-lore-continuation-panel").hide();$.post("https://4cdi46fse8.execute-api.us-west-1.amazonaws.com/Prod/tr",JSON.stringify({command:"get_continuation",cache_id:a}),function(c){_tf14_helper(a,c)})}
function _tf14_helper(a,c){_rj=c;$("#tr-lore-continuation-panel").html("");$("#tr-lore-continuation-panel").append('<div class="tr-subheading">*** WRYTE ***</div>');d='<ul><li><a target=_ href="edit.html?id=7290de613a94a8b582e7e86a91570a93">Not template, Brian! I said "blank slate"</a></li><li><a target=_ href="edit.html?id=6aa1538c6226429a1305d3dab1f1a71d">A blank slate is the bestest slate</a></li><li><a target=_ href="edit.html?id='+(a+'">Fork this shcript. I can do so much better.</a></li></ul>');
$("#tr-lore-continuation-panel").append(d);if(0!=Object.entries(c).length){var b=c.pos;if(b&&2==b.length){var e=b[1][0];b=b[1][1];$("#tr-lore-continuation-panel").append('<div class="tr-subheading">*** POPULAR CONTINUATIONS ***</div>');var d="<ul>";if(e.length&&e[0].length)for(var f=0;f<e.length;f++){a=e[f][0];var g=e[f][1];a&&(g="<a href=?id="+a+"> ... by "+g+" ...</a>",d+="<li>"+g+"</li>")}else d+='<li><a href="edit.html?id=7290de613a94a8b582e7e86a91570a93">Maybe you should write one</a></li>';
d+="</ul>";$("#tr-lore-continuation-panel").append(d);$("#tr-lore-continuation-panel").append('<div class="tr-subheading">*** PUT HERE BY THE BOSS ***</div>');d="<ul>";if(b.length&&b[0].length)for(f=0;f<b.length;f++)a=b[f][0],g=b[f][1],a&&(g="<a href=?id="+a+"> ... by "+g+" ...</a>",d+="<li>"+g+"</li>");else d+='<li><a href="edit.html?id=6aa1538c6226429a1305d3dab1f1a71d">Give him a piece of your mind</a></li>';d+="</ul>";$("#tr-lore-continuation-panel").append(d)}}}
function _tf16(){var a=$("#tr-lore-container .tr-message"),c=$("#tr-lore-container").height();if(a&&c&&_rj){var b=!1;if(0==a.length)b=!0;else{var e=$("#tr-lore-container").offset().top;a=a[a.length-1];e=$(a).offset().top-e+$(a).height()/2+20;0<e&&e<c&&(b=!0)}b&&!$("#tr-lore-continuation-panel").is(":visible")?$("#tr-lore-continuation-panel").fadeIn():!b&&$("#tr-lore-continuation-panel").is(":visible")&&$("#tr-lore-continuation-panel").fadeOut()}}
function _tf17(){$("#tr-set-voices-button").show()}function _tf18(){_rh=!0;$("#tr-title").attr("contentEditable",!0);$("#tr-subtitle").attr("contentEditable",!0);$(".tr-message").attr("contentEditable",!0);$("#tr-set-voices-button").on("click",_tf26);$("#tr-toggle-lines-button").on("click",_tf19);_tf30()}
function _tf19(){var a=_tf21();1==a.length?TR_backup_lines&&1<TR_backup_lines.length&&(console.log("restoring backup"),_tf20(TR_backup_lines)):(console.log("replacing with empty script"),TR_backup_lines=a,_tf20(["NARRATOR: Nothing here but your actors with nothing to do."]))}function _tf20(a){$("#tr-lore").html("");cursor=$('<div style="height:150px;"></div>').appendTo("#tr-lore");cursor=_tf40(a,cursor);return cursor=$('<div style="height:250px;"></div>').insertAfter(cursor)}
function _tf21(){for(var a=[],c=$(".tr-message"),b=0;b<c.length;b++){var e=_tf22($(c[b]).html());e&&a.push(e)}return a}function _tf22(a){a=a.replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"');a=a.replace(/[^\x00-\x7F]/g,"").trim();a=_tf23(a);a=a.replace(/<[^>]*>/g,"");return a=_tf24(a)}function _tf23(a){return a.replace("<b>","^b^").replace("</b>","^/b^")}function _tf24(a){return a.replace("^b^","<b>").replace("^/b^","</b>")}
function _tf25(a,c){if(a&&!c||c&&!a)return!1;if(!a)return!0;if(a.length!=c.length)return!1;for(var b=0;b<a.length;b++)if(a[b]!=c[b])return!1;return!0}
function _tf26(){if($("#tr-your-voice-actors-panel").is(":visible")||$("#tr-select-voice-for-speaker-panel").is(":visible"))$("#tr-your-voice-actors-panel").fadeOut(),$("#tr-select-voice-for-speaker-panel").fadeOut();else{var a='<table id="tr-voices-table">',c=_tf27(),b;for(b in c)a+='<tr><td class="tr-voices-table-speaker">'+b+'</td><td class="tr-voices-table-voice">'+(_rm&&b in _rm?_rm[b]:"Joanna")+"</td></tr>\n";a+="</table>\n";$("#tr-your-voice-actors-table").html($(a));$("#tr-your-voice-actors-panel").fadeIn();
$("#tr-voices-table .tr-voices-table-voice").off("click").on("click",function(){_tf28(this)})}}function _tf27(){for(var a=$(".tr-message"),c={},b=0;b<a.length;b++){var e=$(a[b]).html();e&&(e=_tf22(e).replace(/:.*/,"").trim())&&(c[e]=!0)}return c}
function _tf28(a){$("#tr-select-voice-for-speaker-panel").fadeIn();var c=$(a).prev().text();$("#tr-speaker-name").html(c);$("#tr-select-voice-for-speaker-panel li").off("click").on("click",function(){var b=$(this).text().replace(/ -.*/,""),c=$(a).html();b!=c&&($(a).html(b),$(a).css({color:"white"}),_tf31(),$("#tr-select-voice-for-speaker-panel").hide())})}function _tf29(a){return a.replace(/ -.*/,"")}
function _tf30(){$("#tr-select-voice-for-speaker-panel ul").html("<li>Joanna - US English - Female</li><li>Matthew - US English - Male</li><li>Salli - US English - Female</li><li>Kendra - US English - Female</li><li>Kimberly - US English - Female</li><li>Joey - US English - Male</li><li>Ivy - US English - Female (child)</li><li>Justin - US English - Male (child)</li><li>Russell - Australian English - Male</li><li>Nicole - Australian English - Female</li><li>Amy - British English - Female</li><li>Brian - British English - Male</li><li>Emma - British English - Female</li><li>Raveena - Indian English - Female</li><li>Aditi - Indian English - Female</li><li>Geraint - Welsh English - Male</li>")}
function _tf31(){var a=$(".tr-voices-table-speaker"),c=$(".tr-voices-table-voice");speaker_map_changed=!1;for(var b=0;b<a.length;b++)speaker=$(a[b]).text(),voice=$(c[b]).text().replace(/ -.*/,""),_rm[speaker]!=voice&&(_rm[speaker]=voice,speaker_map_changed=!0);speaker_map_changed&&(_ra=null,_rc=0,_tf8())}function _tf32(){_rf&&(_rf=!1,_tf35("tr-lore-container","tr-message","tr-current"),_tf35("tr-lore-trail-selector","tr-lore-trail-option","tr-current",1))}
function _tf33(){_rg&&(_rg=!1,_tf34($("#tr-your-voice-actors-panel")),_tf34($("#tr-select-voice-for-speaker-panel")),_tf34($("#tr-lore-continuation-panel")),$("#tr-curtain").height($(window).height()),$("#tr-curtain").width($(window).width()))}function _tf34(a){a.css({left:(window.innerWidth-a.width())/2+"px"})}
function _tf35(a,c,b,e){var d=$("#"+a).height();if((c=$("#"+a+" ."+c))&&c.length){a=$("#"+a).offset().top;for(var f=0;f<c.length;f++){var g=c[f],h=$(g).offset().top-a+$(g).height()/2;if(!(-100>h)){if(h>d+100)break;h=Math.abs(Math.sin(Math.PI*h/d));e&&1!=e&&(h=Math.pow(h,e));var k=1+.1*h;$(g).css({opacity:h,transform:"scale("+k+")"});.9>=h?(b&&$(g).removeClass(b),$(g).off("click")):b&&$(g).addClass(b)}}}}
function _tf36(a){switch(a.keyCode){case 10:case 13:$(this).html().endsWith("<div><br></div>")&&(a=$(this).html().replace("<div><br></div>",""),$(this).html(a),_tf43(this,"").focus());break;case 8:1!=$(".tr-message").length&&""==$(this).text()&&($(this).prev().focus(),_tf37($(this).prev()),$(this).remove(),_rf=!0)}}function _tf37(a){var c=document.createRange();c.selectNodeContents(a[0]);c.collapse(!1);selection=window.getSelection();selection.removeAllRanges();selection.addRange(c)}
function _tf38(a){var c=a.originalEvent.clipboardData.getData("Text");if(!(100>c.length))return a.preventDefault(),c=c.replace("<br>","\n").replace(/<[^>]*>/g,"").split("\n"),"script"==_tf39(c)?_tf41(c,a.currentTarget):_tf40(c,a.currentTarget)}
function _tf39(a){for(var c=0,b=!1;25>c&&c<a.length;)if(a[c++].match(/^[0-9A-Z][0-9A-Z ]*$/)){b=!0;break}if(!b)return"unknown";for(b=!1;50>c&&c<a.length;)if(a[c++].match(/ *[0-9]+ (INT)|(EXT)[.] /)){b=!0;break}if(!b)return"unknown";for(b=!1;100>c&&c<a.length;)if(a[c++].match(/^ {1,} *[^a-z]+$/)){b=!0;break}return b?"script":"unknown"}
function _tf40(a,c){for(var b="",e=0;e<=a.length;e++){if(e<a.length){var d=a[e].replace(/  */g," ").trim();if(!d.match(/^ *[A-Z][A-Z.\(\) ]*:/)){b=""==b?"NARRATOR: "+d:b+" "+d;continue}}b.trim()&&(c=_tf42(b,c));b=d}return c}
function _tf41(a,c){for(var b="NARRATOR",e,d,f=0;f<a.length&&(d=a[f++].replace(/<[^>]*>/g,""),!d.match(/^[0-9A-Z][0-9A-Z ]*$/)););for($("#tr-title").html(d);f<a.length&&(d=a[f++].replace(/<[^>]*>/g,""),!d.match(/ *[0-9]+ (INT)|(EXT)[.] /)););$("#tr-subtitle").html(d);e="";for(var g="NARRATOR";f<a.length;)if(d=a[f++].replace(/<[^>]*>/g,"")){if(d.match(/ *[0-9]+ (INT)|(EXT)[.] /)){console.log("Imported up to next scene match in:"+d);break}" "!=d[0]?b="NARRATOR":d.match(/^ {1,} *([^a-z]+)$/)&&(b=d.trim(),
d="");if(b!=g||f==a.length-1){var h=e.replace(/\s+/g," ").trim();h&&(c=_tf42(g+": "+h,c),e=" "==d[0]?d:"");g=b}d.trim()&&(e+=" "+d.trim())}return c}function _tf42(a,c){if(a.trim())return _tf43(c,a)}function _tf43(a,c){var b=$('<div class="tr-message"></div>');b.html(c);_rh&&(b.attr("contentEditable",!0),b.keyup(_tf36),b.on("paste",_tf38));b.insertAfter($(a));_rf=!0;return b};

