var _q22=null,_q3=new Audio("/aud/q-ting.mp3"),_q5=new Audio("/aud/q-cloud-test.mp3"),_q17=null,_q16=!1,_q30=new Audio("/aud/yes-chord.mp3"),_q29=new Audio("/aud/no-chord.mp3");
function _q4(a){_q20(_q5);$("#_imgspin_box").removeClass("q-results-ready-msg");$("#_imgspin_box").addClass("q-wait-msg");$(".q-screen").fadeIn();_imgspin_start_spinner();var b=$("#q-id").text();$.post("/php/q-do-cloud-test.php",{u:a,id:b},function(a){_q22=a;$("#_imgspin_box").removeClass("q-wait-msg");$("#_imgspin_box").addClass("q-results-ready-msg");$("#_imgspin_img").attr("onclick","_q1()");_q20(_q3);_q25()})}function _q20(a){a=a.play();void 0!==a&&a.then(function(a){}).catch(function(a){})}
function _q21(a){if(null!=a){if(27==a.which&&""!=$("#q-text-input-text").val())$("#q-text-input-text").val(""),_q16=!1,_q17="",_q25();else if(13==a.which||10==a.which)a=$("#q-text-input-text").val().trim().toLowerCase(),""!=a?_q16&&($("#q-text-input-text").val(""),_q4(a)):null!=_q22?(_q18(),_q2()):_q7();_q14()}}function _q14(){var a=$("#q-text-input-text").val();a=20>=a.length?33:33-.5*(a.length-20);12>a&&(a=12);$("#q-text-input-text").css("font-size",a+"px")}
function _q26(){_q20(_q30);$("#q-text-input-div").addClass("q-valid-id");$("#q-text-input-text").addClass("q-valid-id")}function _q25(){_q20(_q29);_q16=!1;$("#q-text-input-div").removeClass("q-valid-id");$("#q-text-input-text").removeClass("q-valid-id")}
function _q15(a,b,g){var d=$("#q-text-input-text").val().trim().toLowerCase();"undefined"==typeof d||""==d||null!=_q17&&d==_q17&&!g||($.get("/php/q-check-host.php?u="+d,function(c){c=JSON.parse(c);if(null!=c&&0==c.e){if(g||!_q16)null!=a&&a(),_q16=!0}else if(g||_q16)null!=b&&b(),_q16=!1}),_q17=d)}function _q27(){_q15(_q26,_q25,!1);_q14()}$(document).ready(function(){$("body").fadeIn();$("#q-text-input-text").keyup(_q21);_q6("Click on the quest name for the program spec");setInterval(_q27,100)});
function _q23(){$("#q-results-container").fadeOut();$(".q-usermsg").fadeIn(2E3,"swing",function(){$(".q-usermsg").fadeOut(3E3)});$("#q-text-input-text").focus()}function _q2(){$("#q-results-container").fadeIn();null==_q22?$(".q-result-link").addClass("disabled"):$(".q-result-link").removeClass("disabled")}function _q1(){$("#_imgspin_img").attr("onclick",null);null!=_q22&&_q18();_q2();$(".q-screen").fadeOut();_imgspin_stop_spinner()}function _q7(){_q8($("#q-id").text());_q2()}
function _q20(a){a=a.play();void 0!==a&&a.then(function(a){}).catch(function(a){})}function _q6(a){var b=$("#q-usermsg").html();$(".q-usermsg").html(a);$(".q-usermsg").fadeIn(1E3,"swing",function(){$(".q-usermsg").fadeOut(3E3,function(){$(".q-usermsg").html(b)})})}function _q10(){$(".q-error").fadeIn()}function _q18(){_q13();_q2()}function _q28(a){$("#q-results").fadeOut("fast",function(){$("#q-results").html(a);$("#q-results").fadeIn(_q12)})}
function _q8(a){$(".q-result-link").css("font-weight","normal");$("#q-spec").css("font-weight","bold");a=$("#q-id").text();a='<object class="q-pdf" data="/php/q-get-spec.php?id='+a+'" type="application/pdf"></object>';$("#q-results").html(a);_q2()}
function _q13(){$(".q-result-link").css("font-weight","normal");$("#q-comp").css("font-weight","bold");var a="<h2>Build Messages</h2>";null==_q22?_q28(a+"<p>You haven't submitted your code yet.</p><p>&amp;</p>"):(a+="<p>If you don't see any errors or warnings on this page, that means your code built without any issues.</p><p>If it says my test program got terminated, it means that it ran longer than I expected it to run.</p><p>In that case expect my test output to be empty.</p>",""!=_q22.t&&(a+=_q22.b),
""!=_q22.t&&(a+="<p>You can see <a href='javascript:_q9();'>what happened when I tried to run it</a>.</p>"),""!==_q22.m&&(a+="<p>And you may want to review its <a href='javascript:_q11();'>Memory leakage analysis</a>.</p>"),_q28(a+"<p>&amp;</p>"))}
function _q11(){$(".q-result-link").css("font-weight","normal");$("#q-valg").css("font-weight","bold");var a="<h2>Memory Check</h2>";null==_q22?_q28(a+"<p>You haven't submitted your code yet.</p><p>&amp;</p>"):(a+="<p>If your program ran successfully, don't worry about the part below that reports one extra alloc and blocks reachable at exit.</p><p>I've isolated that issue to <em>iostream.h</em> and confirmed that it's benign enough for now. On ubuntu:xenial, you can reproduce this by valgrinding a binary from:</p><PRE>    #include &lt;iostream&gt;\n    int main() {}\n</PRE><p>If you have other serious memory leaks reported below, you should strive to fix those.</p><p>And note that you may not see any output if the program got terminated.</p><p>&amp;</p><PRE>"+_q22.m+
"</PRE>",_q28(a))}
function _q9(){$(".q-result-link").css("font-weight","normal");$("#q-prog").css("font-weight","bold");var a="<h2>Test Output</h2>";null==_q22?_q28(a+"<p>You haven't submitted your code yet.</p><p>&amp;</p>"):(""==_q22.t.trim()&&(a+="<p>BTW, you may not see any output here if my test got terminated, usually because it didn't finish in time.</p>"),a+=_q24(_q22.t),""!==_q22.m.trim()&&(a+="<p>There seem to be <a href='javascript:_q11();'>memory issues</a> you must review (may be benign)</p>"),_q28(a))}
function _q12(){if(0!=$("#q_graph_0").length)for(var a=0;a<q_graphs.length;a++)q_show_graph(q_graphs[a],"q_graph_"+a)}
function _q24(a){var b="";a=a.split("\n");var g=!1,d=null,c=-1,h="";q_graphs=[];for(var e=0;e<a.length;e++)if("# Graph "==a[e].trim().substring(0,8))g=!0,h+=a[e]+"<br/>",c=-1,d={nodes:[],edges:[]},b+="</pre>\n";else if("# End of Graph"==a[e]){g=!1;h+=a[e]+"<br/>";b+="<div class=q-code>"+h+"</div>";h="";for(var f=0;f<=c;f++)d.nodes.push({n:f});b+="\nHerein Be Da Graph #"+q_graphs.length+":</br>\n<div class=q_graph_div id=q_graph_"+q_graphs.length+"></div>";q_graphs.push(d);b+="<pre>\n"}else if(g){h+=
a[e]+"<br/>";f=a[e].split(" ");var m=parseInt(f[0]);m>c&&(c=m);for(var l=2;l<f.length&&"#"!=f[l][0];l++){var k=f[l].replace(/[)(,]/g," ").trim().split(" ");if(!(2>k.length)){var n=parseInt(k[0]);k=""+k[1];n>c&&(c=n);d.edges.push({source:m,target:n,w:k})}}}else b+=a[e]+"\n";return b};
