// Sample Json to stick in the input window
// for inspiration
//
var SceneJsonStr = 
      '{\n'
    + ' "name": "room",\n'
    + ' "children": [\n'
    + '  {\n'
    + '   "name": "table",\n'
    + '   "children": [\n'
    + '    {\n'
    + '     "name": "south west leg"\n'
    + '    },\n'
    + '    {\n'
    + '     "name": "south east leg"\n'
    + '    },\n'
    + '    {\n'
    + '     "name": "north west leg"\n'
    + '    },\n'
    + '    {\n'
    + '     "name": "north east leg"\n'
    + '    }\n'
    + '   ]\n'
    + '  },\n'
    + '  {\n'
    + '   "name": "Lily the canine",\n'
    + '   "children": [\n'
    + '    {\n'
    + '     "name": "torso",\n'
    + '     "children": [\n'
    + '      {\n'
    + '       "name": "wagging tail"\n'
    + '      },\n'
    + '      {\n'
    + '       "name": "spare mutant paw"\n'
    + '      },\n'
    + '      {\n'
    + '       "name": "left rear paw"\n'
    + '      },\n'
    + '      {\n'
    + '       "name": "right rear paw"\n'
    + '      },\n'
    + '      {\n'
    + '       "name": "Right front paw"\n'
    + '      },\n'
    + '      {\n'
    + '       "name": "right front paw"\n'
    + '      }\n'
    + '     ]\n'
    + '    }\n'
    + '   ]\n'
    + '  },\n'
    + '  {\n'
    + '   "name": "Miguel the human",\n'
    + '   "children": [\n'
    + '    {\n'
    + '     "name": "torso",\n'
    + '     "children": [\n'
    + '      {\n'
    + '       "name": "Right arm",\n'
    + '       "children": [\n'
    + '        {\n'
    + '         "name": "Right hand",\n'
    + '         "children": [\n'
    + '          {\n'
    + '           "name": "pinky"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "ring finger"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "middle finger"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "index finger"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "thumb"\n'
    + '          }\n'
    + '         ]\n'
    + '        }\n'
    + '       ]\n'
    + '      },\n'
    + '      {\n'
    + '       "name": "left arm",\n'
    + '       "children": [\n'
    + '        {\n'
    + '         "name": "left hand",\n'
    + '         "children": [\n'
    + '          {\n'
    + '           "name": "pinky"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "ring finger"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "middle finger"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "index finger"\n'
    + '          },\n'
    + '          {\n'
    + '           "name": "thumb"\n'
    + '          }\n'
    + '         ]\n'
    + '        }\n'
    + '       ]\n'
    + '      }\n'
    + '     ]\n'
    + '    }\n'
    + '   ]\n'
    + '  }\n'
    + ' ]\n'
    + '}\n'
    + '\n'
;
