var SceneLtnStr = [
 "room",
 " table",
 "  south west leg",
 "  south east leg",
 "  north west leg",
 "  north east leg",
 " Miguel the human",
 "  torso",
 "   right arm",
 "    right hand",
 "     pinky",
 "     ring finger",
 "     middle finger",
 "     index finger",
 "     thumb",
 "   left arm",
 "    left hand",
 "     pinky",
 "     ring finger",
 "     middle finger",
 "     index finger",
 "     thumb",
 " Lily the canine",
 "  torso",
 "   wagging tail",
 "   spare mutant paw",
 "   left rear paw",
 "   right rear paw",
 "   left front paw",
 "   right front paw"
];
